# MySql Database Configuration
spring.application.name=gamerent
spring.config.import=optional:secrets.properties
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

# JPA Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security default user credentials for development
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=USER
